apiVersion: v1
name: forecastle
description: forecastle chart that runs on kubernetes
icon: https://github.com/stakater/Forecastle/raw/master/assets/web/forecastle-round-100px.png
version: v1.0.113
keywords:
  - forecastle
  - kubernetes
home: https://github.com/stakater/Forecastle
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io
