apiVersion: v2
name: forecastle
description: forecastle chart that runs on kubernetes
icon: https://github.com/stakater/Forecastle/raw/master/assets/web/forecastle-round-100px.png
version: 1.2.0
appVersion: "v2.0.0"
keywords:
  - forecastle
  - kubernetes
home: https://github.com/stakater/Forecastle
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io
