apiVersion: v1
name: forecastle
description: forecastle chart that runs on kubernetes
version: v1.0.42
keywords:
  - forecastle
  - kubernetes
home: https://github.com/stakater/Forecastle
maintainers:
- name: Stakater
  email: stakater@aurorasolutions.io
